# Generated by Django 4.2 on 2023-05-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Criado em')),
                ('update_at', models.DateField(verbose_name='Editado em')),
                ('deleted_at', models.DateField(editable=False, verbose_name='Excluido em')),
                ('title', models.CharField(max_length=30, verbose_name='Titulo')),
                ('descripition', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('version', models.IntegerField(default=1, verbose_name='Versão da Edição')),
                ('publisher', models.CharField(max_length=150, verbose_name='Noma da Editora')),
                ('isbn', models.CharField(max_length=30, verbose_name='Identificador')),
                ('code', models.CharField(blank=True, help_text='Código gerado automaticamente', max_length=8, null=True, verbose_name='Código do Livro')),
                ('author', models.CharField(max_length=100, verbose_name='Nome do Autor')),
            ],
        ),
    ]
