# Generated by Django 4.2 on 2023-05-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AlterField(
            model_name='book',
            name='deleted_at',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Excluido em'),
        ),
        migrations.AlterField(
            model_name='book',
            name='update_at',
            field=models.DateField(blank=True, null=True, verbose_name='Editado em'),
        ),
    ]
